/*KEVIN BREWTON*/
/*Phone number of O'Shea family*/
SELECT PHONE FROM FAMILY_PACKAGE WHERE ID=2;
/*NAMES OF INSTRUCTORS AND CLASSES THEY TEACH*/
SELECT INSTRUCTOR.F_NAME, INSTRUCTOR.L_NAME, CLASS.TITLE FROM INSTRUCTOR, CLASS WHERE CLASS.INSTRUCTOR = INSTRUCTOR.ID;
/*NAMES OF MEMBERS WHOSE ADDRESS AND PHONE NUMBERS ARE NOT KNOWN*/
SELECT F_NAME, L_NAME FROM RECCENTERMEMBER WHERE FAMILY_ID IS NULL;
/*NAMES OF MEMBERS WHO'VE TAKEN CRAFT OR ART CLASS*/
SELECT F_NAME, L_NAME FROM RECCENTERMEMBER WHERE ID IN (SELECT MEMBER_ID FROM ENROLLMENT WHERE CLASS_ID IN (1,2,3,7,8));
/*NAMES OF THOSE WHO HAVEN'T TAKEN ANY CLASS SINCE SPRING 2009*/
SELECT F_NAME, L_NAME FROM RECCENTERMEMBER WHERE ID IN (SELECT MEMBER_ID FROM ENROLLMENT WHERE CLASS_ID NOT IN (1,6,7));
/*NAME OF INSTRUCTORS AND DESCRIPTION OF CLASSES THEY TAUGHT IN  BOTH SPRING AND FALL 2009*/
SELECT INSTRUCTOR.F_NAME, INSTRUCTOR.L_NAME, DESCRIPTION FROM INSTRUCTOR, (SELECT TYPE.DESCRIPTION FROM TYPE WHERE TYPE.TYPE IN (SELECT CLASS.TYPE FROM CLASS WHERE CLASS.SEASON IN ('Spring', 'Fall') AND CLASS.YEAR = 2009)) WHERE INSTRUCTOR.ID IN (SELECT CLASS.INSTRUCTOR FROM CLASS WHERE (SEASON IN ('Spring', 'Fall') AND YEAR = 2009)); 
/*TYPES OF CLASSES OFFERED IN 2008 AND 2009 ALONG WITH DESCRIPTIONS*/
SELECT TYPE.TYPE, TYPE.DESCRIPTION FROM TYPE WHERE TYPE.TYPE IN (SELECT CLASS.TYPE FROM CLASS WHERE (CLASS.YEAR = 2009 OR CLASS.YEAR = 2008));
